<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="securifybv.ShellLink" Version="0.1.0" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SH.Content\SH.Content.csproj" />
    <ProjectReference Include="..\SH.Framework\SH.Framework.csproj" />
    <ProjectReference Include="..\SH.Modding\SH.Modding.csproj" />
  </ItemGroup>
  
</Project>
