<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RootNamespace>SH.Launcher</RootNamespace>
    <AssemblyName>SpaceHavenLauncher</AssemblyName>
		<Copyright>Ghostkeeper666</Copyright>
    <ApplicationIcon>SpaceHavenLauncher.ico</ApplicationIcon>
		<AssemblyTitle>Space Haven Launcher</AssemblyTitle>    
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
		<AvaloniaResource Update="Assets\Icons\Icons.axaml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
    <AvaloniaXaml Remove="Assets\Icons\Icons.axaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.3" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.3" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Markdig" Version="1.2.0" />
    <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SH.Content\SH.Content.csproj" />
    <ProjectReference Include="..\SH.Framework\SH.Framework.csproj" />
    <ProjectReference Include="..\SH.Launcher.Core\SH.Launcher.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="aspectj-1.9.19.jar">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="aspectjweaver-1.9.19.jar">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Icons\SpaceHavenLauncher.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="LauncherAgent.jar">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\000-Welcome!.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\200_Space_Haven_Basics.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\210-haven.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\220-texts.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\250-spacehavensettings.xml.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\260-config.json.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\300-Modding_Basics.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\010-A_new_modding_tool.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\340-background.jpg_file.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\330-description.md_file.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\310-INFO.XML_file.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\320-MOD ID_versus_ AUTO ID.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\400-XML_Mod_Overview.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\430-Modding_Textures.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\440-Modding_Audio.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\499-XML_Mod_Tutorial.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\240-textures_and_animations.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\230-audio.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\410-Merging_XML.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\420-Patching_XML.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\699-JAVA_Mod_Tutorial.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\600-JAVA_Mod_Overview.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\999-Credits.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\audio\facility_newjukebox.ogg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\background.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\description.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\info.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\library\animations_NewJukebox.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\library\audio_NewJukebox.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\library\haven_NewJukebox.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\library\texts_NewJukebox.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\patches\audio_patch_NewJukebox.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\patches\haven_patch_NewJukebox.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\textures\newjukebox1064.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\textures\newjukebox142.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\textures\newjukebox143.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\textures\newjukebox5438.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Learning\XmlModTutorial\textures\newjukebox700.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="README.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SpaceHaven.icns">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SpaceHavenLauncher.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
